---
# ansible/playbook-cuckoo.yml
- name: Provision Cuckoo Sandbox Host (Ubuntu 22.04)
  hosts: all
  become: true
  vars:
    cuckoo_user: cuckoo
    cuckoo_home: /home/cuckoo
    python_bin: /usr/bin/python3
  tasks:
    - name: Ensure apt cache updated
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install base packages
      apt:
        name:
          - git
          - build-essential
          - python3
          - python3-venv
          - python3-pip
          - python3-dev
          - libffi-dev
          - libssl-dev
          - zlib1g-dev
          - libjpeg-dev
          - swig
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - virtinst
          - bridge-utils
          - libguestfs-tools
          - mongodb
          - postgresql
          - libpq-dev
          - tcpdump
          - tshark
        state: present
      tags: packages

    - name: Create cuckoo user
      user:
        name: "{{ cuckoo_user }}"
        shell: /bin/bash
        create_home: yes
        groups: libvirt
        append: yes

    - name: Add cuckoo user to kvm and libvirt groups
      user:
        name: "{{ cuckoo_user }}"
        groups: "kvm,libvirt"
        append: yes

    - name: Clone Cuckoo repository into home
      git:
        repo: https://github.com/cuckoosandbox/cuckoo.git
        dest: "{{ cuckoo_home }}/cuckoo"
        version: master
        force: yes
      become_user: "{{ cuckoo_user }}"

    - name: Create Python venv and install requirements
      become_user: "{{ cuckoo_user }}"
      shell: |
        cd {{ cuckoo_home }}/cuckoo
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt || true
        pip install -e .
      args:
        executable: /bin/bash

    - name: Create basic cuckoo config directory if missing
      file:
        path: "{{ cuckoo_home }}/.cuckoo"
        state: directory
        owner: "{{ cuckoo_user }}"
        group: "{{ cuckoo_user }}"
        mode: '0755'

    - name: Copy sample config files (user must review and edit)
      copy:
        src: "{{ item.src }}"
        dest: "{{ cuckoo_home }}/.cuckoo/{{ item.dest }}"
        owner: "{{ cuckoo_user }}"
        group: "{{ cuckoo_user }}"
        mode: '0644'
      with_items:
        - { src: "cuckoo/conf/cuckoo.conf.sample", dest: "cuckoo.conf" }
      tags: config
      ignore_errors: yes

    - name: Ensure libvirtd service running
      service:
        name: libvirtd
        state: started
        enabled: yes

    - name: Print next steps
      debug:
        msg: |
          Cuckoo base installed. Next steps:
            - Review and edit {{ cuckoo_home }}/.cuckoo/cuckoo.conf, machines.conf, auxiliary.conf
            - Prepare guest VMs (Windows images or Linux) and install the Cuckoo agent in each guest.
            - Configure a dedicated bridge/network for guest traffic and pcap capture.
            - Start cuckoo as the cuckoo user in the venv: source venv/bin/activate && cuckoo
